name: Sync Assets to GCS

on:
  push:
    branches: [ main ]
    paths:
      - 'assets/places/**'
  # 如需手動同步，另外加：
  # workflow_dispatch:

jobs:
  sync:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Auth to GCP (WIF)
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.DEPLOY_SA_EMAIL }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Rsync images to GCS
      run: |
        gsutil -m rsync -r ./assets/places gs://${{ vars.ASSET_BUCKET }}/places
        # 設定強快取（1年），避免重載
        gsutil -m setmeta -h "Cache-Control:public,max-age=31536000,immutable" gs://${{ vars.ASSET_BUCKET }}/places/** || true
