name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  # workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.DEPLOY_SA_EMAIL }}
          # 使用預設 ADC 憑證（不要設定 token_format）

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        # 不傳 project_id，避免自動跑 `gcloud config set project`

      - name: Docker login (use ADC from auth step)
        run: |
          ACCESS_TOKEN=$(gcloud --project=${{ vars.PROJECT_ID }} auth print-access-token)
          echo "$ACCESS_TOKEN" | docker login -u oauth2accesstoken --password-stdin \
            ${{ vars.REGION }}-docker.pkg.dev

      - name: Build & Push image
        env:
          IMAGE: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPO }}/app:${{ github.sha }}
        run: |
          echo "IMAGE=${IMAGE}"
          docker build -t "${IMAGE}" .
          docker push "${IMAGE}"
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying SERVICE=${{ vars.SERVICE_NAME }} to PROJECT=${{ vars.PROJECT_ID }} in REGION=${{ vars.REGION }}"
          gcloud --project=${{ vars.PROJECT_ID }} run deploy ${{ vars.SERVICE_NAME }} \
            --image "${IMAGE}" \
            --region ${{ vars.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --service-account cr-runtime@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com \
            --cpu 1 --memory 512Mi \
            --concurrency 10 --timeout 10s \
            --min-instances 1 \
            --set-env-vars=ASSET_BASE_URL=https://storage.googleapis.com/${{ vars.ASSET_BUCKET }} \
            --set-secrets=CHANNEL_SECRET=CHANNEL_SECRET:latest,CHANNEL_ACCESS_TOKEN=CHANNEL_ACCESS_TOKEN:latest
